version: '3'

volumes:
  testing_postgres_data: { }
  testing_postgres_data_backups: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: makro_uz_testing_django
    environment:
      - STAGE=dev
    volumes:
      - /var/www/testing.makro.uz/media:/app/makro_uz/media
      - /var/www/testing.makro.uz/static:/app/makro_uz/static
    depends_on:
      - postgres
      - redis
    ports:
      - 5002:5000
    env_file:
      - ./.envs/.development/.django
      - ./.envs/.development/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: makro_uz_testing_postgres
    volumes:
      - testing_postgres_data:/var/lib/postgresql/data
      - testing_postgres_data_backups:/backups
    env_file:
      - ./.envs/.development/.postgres

  redis:
    image: redis:6

  mongodb:
    image: mongo:latest
    container_name: mongodb_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"

  celeryworker:
    <<: *django
    image: makro_uz_testing_celeryworker
    container_name: makro_uz_testing_celeryworker
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: makro_uz_testing_celerybeat
    container_name: makro_uz_testing_celerybeat
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celerybeat
