# Generated by Django 4.2.5 on 2024-01-08 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0018_remove_newscatalog_photo_newscatalog_photo_ru_and_more"),
        ("discount", "0012_discountcatalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("display_order", models.IntegerField(default=0, verbose_name="Порядок отображения")),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="discount.discount"
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="news.news"
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент карусели",
                "verbose_name_plural": "Элементы карусели",
            },
        ),
    ]
