# Generated by Django 4.2.5 on 2024-09-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_alter_carouselitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='carouselImage', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='photo_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='carouselImageMobile', verbose_name='Изображение для мобилки'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для перехода'),
        ),
    ]
