# Generated by Django 4.2.5 on 2023-09-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="status",
            field=models.IntegerField(choices=[(1, "ACTIVE"), (2, "ARCHIVE")], default=1),
        ),
    ]
