# Generated by Django 4.2.3 on 2023-09-23 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0006_alter_discount_enddate_alter_discount_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="endDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="discount",
            name="startDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
