# Generated by Django 4.2.3 on 2023-09-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0008_alter_discount_enddate_alter_discount_startdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="discount",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Название"),
        ),
    ]
