# Generated by Django 4.2.3 on 2023-09-29 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0009_discount_description_discount_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="endDateFile",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True, verbose_name="Файл Время окончания"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploadFiles", verbose_name="Файл"),
        ),
        migrations.AddField(
            model_name="discount",
            name="titleFile",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Название Файл"),
        ),
    ]
