# Generated by Django 4.2.3 on 2023-10-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0010_discount_enddatefile_discount_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="discount",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="discount",
            name="titleFile_ru",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Название Файл"),
        ),
        migrations.AddField(
            model_name="discount",
            name="titleFile_uz",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Название Файл"),
        ),
        migrations.AddField(
            model_name="discount",
            name="title_ru",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="discount",
            name="title_uz",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Название"),
        ),
    ]
