# Generated by Django 4.2.5 on 2023-11-11 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0011_discount_description_ru_discount_description_uz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "photo_uz",
                    models.ImageField(
                        blank=True, null=True, upload_to="discountCatalogImage", verbose_name="Изображение uz"
                    ),
                ),
                (
                    "photo_ru",
                    models.ImageField(
                        blank=True, null=True, upload_to="discountCatalogImage", verbose_name="Изображение ru"
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discountCatalog",
                        to="discount.discount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
