# Generated by Django 4.2.5 on 2024-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0015_discount_photo_mobile_alter_discount_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
    ]
