# Generated by Django 4.2.5 on 2024-08-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0016_discount_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Показать на главной?'),
        ),
    ]
