# Generated by Django 4.2.5 on 2024-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0017_discount_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='photo_app',
            field=models.ImageField(blank=True, null=True, upload_to='discountImageMobile', verbose_name='Изображение для приложения'),
        ),
    ]
