# Generated by Django 4.2.5 on 2024-09-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0019_discount_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='url',
        ),
    ]
