# Generated by Django 4.2.5 on 2025-02-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0021_discountfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountfiles',
            name='titleFile_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название Файл'),
        ),
        migrations.AddField(
            model_name='discountfiles',
            name='titleFile_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название Файл'),
        ),
    ]
