# Generated by Django 4.2.5 on 2024-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ferma", "0002_toys_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="toys",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="toys",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="toys",
            name="facts_ru",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="toys",
            name="facts_uz",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="toys",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="toys",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="toys",
            name="role_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="toys",
            name="role_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="toys",
            name="short_description_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="toys",
            name="short_description_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
