# Generated by Django 4.2.5 on 2023-09-08 18:17

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("longitude", models.CharField(max_length=40)),
                ("latitude", models.CharField(max_length=40)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("videoURL", models.URLField(blank=True, null=True)),
                ("photo", models.ImageField(upload_to="newsImage", verbose_name="Image of News")),
                ("status", models.IntegerField(choices=[(1, "ACTIVE"), (2, "ARCHIVE")], default=1)),
                ("startDate", models.DateField(default=django.utils.timezone.now)),
                ("endDate", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
