# Generated by Django 4.2.3 on 2023-09-21 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_news_enddate_alter_news_startdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.CharField(default="Toshkent", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="endDate",
            field=models.DateField(default=datetime.date(2023, 9, 21)),
        ),
        migrations.AddField(
            model_name="location",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="startDate",
            field=models.DateField(default=datetime.date(2023, 9, 21)),
        ),
        migrations.AddField(
            model_name="location",
            name="title",
            field=models.CharField(default="Makro", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="endDate",
            field=models.DateField(default=datetime.date(2023, 9, 21)),
        ),
        migrations.AlterField(
            model_name="news",
            name="startDate",
            field=models.DateField(default=datetime.date(2023, 9, 21)),
        ),
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="regionLocation",
                to="news.region",
            ),
        ),
    ]
