# Generated by Django 4.2.3 on 2023-09-21 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_region_location_address_location_enddate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="title",
        ),
    ]
