# Generated by Django 4.2.3 on 2023-09-21 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_remove_location_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="link",
        ),
    ]
