# Generated by Django 4.2.5 on 2023-09-21 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_remove_location_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="endDate",
        ),
        migrations.RemoveField(
            model_name="location",
            name="startDate",
        ),
        migrations.AddField(
            model_name="location",
            name="close",
            field=models.TimeField(default=datetime.time(19, 40, 29, 998495)),
        ),
        migrations.AddField(
            model_name="location",
            name="open",
            field=models.TimeField(default=datetime.time(19, 40, 29, 998487)),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
