# Generated by Django 4.2.3 on 2023-09-23 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_remove_location_enddate_remove_location_startdate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="region",
        ),
        migrations.AlterField(
            model_name="location",
            name="close",
            field=models.TimeField(default=datetime.time(6, 49, 58, 890023)),
        ),
        migrations.AlterField(
            model_name="location",
            name="open",
            field=models.TimeField(default=datetime.time(6, 49, 58, 890015)),
        ),
        migrations.AlterField(
            model_name="news",
            name="endDate",
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
        migrations.AlterField(
            model_name="news",
            name="startDate",
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=150)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="regionDistrict", to="news.region"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="location",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="districtLocation",
                to="news.district",
            ),
        ),
    ]
