# Generated by Django 4.2.3 on 2023-09-23 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_remove_location_region_alter_location_close_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="close",
            field=models.TimeField(default=datetime.time(6, 50, 19, 925974)),
        ),
        migrations.AlterField(
            model_name="location",
            name="open",
            field=models.TimeField(default=datetime.time(6, 50, 19, 925967)),
        ),
    ]
