# Generated by Django 4.2.3 on 2023-09-23 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_alter_location_close_alter_location_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="close",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="location",
            name="open",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="news",
            name="endDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="news",
            name="startDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
