# Generated by Django 4.2.3 on 2023-09-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0011_alter_district_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(max_length=300, verbose_name="Адрес"),
        ),
    ]
