# Generated by Django 4.2.3 on 2023-09-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0012_alter_location_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="title",
            field=models.CharField(default="Makro", max_length=150, verbose_name="Название"),
            preserve_default=False,
        ),
    ]
