# Generated by Django 4.2.3 on 2023-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0014_alter_news_options_remove_news_enddate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="photo_medium",
            field=models.ImageField(
                blank=True, null=True, upload_to="newsImage", verbose_name="Детальное изображение"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="photo",
            field=models.ImageField(upload_to="newsImage", verbose_name="Изображение"),
        ),
    ]
