# Generated by Django 4.2.3 on 2023-10-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0015_news_photo_medium_alter_news_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="title_ru",
            field=models.CharField(max_length=150, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="district",
            name="title_uz",
            field=models.CharField(max_length=150, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="location",
            name="address_ru",
            field=models.CharField(max_length=300, null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="location",
            name="address_uz",
            field=models.CharField(max_length=300, null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="location",
            name="title_ru",
            field=models.CharField(max_length=150, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="location",
            name="title_uz",
            field=models.CharField(max_length=150, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="news",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="news",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ru",
            field=models.CharField(max_length=150, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_uz",
            field=models.CharField(max_length=150, null=True, verbose_name="Название"),
        ),
    ]
