# Generated by Django 4.2.5 on 2023-11-11 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0016_district_title_ru_district_title_uz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("photo", models.ImageField(upload_to="newsCatalogImage", verbose_name="Изображение")),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="newsCatalog", to="news.news"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
