# Generated by Django 4.2.5 on 2024-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0018_remove_newscatalog_photo_newscatalog_photo_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="newscatalog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
