# Generated by Django 4.2.5 on 2024-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0020_alter_news_description_alter_news_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="photo_medium_mobile",
            field=models.ImageField(
                blank=True, null=True, upload_to="newsImageMobile", verbose_name="Детальное изображение"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="photo_mobile",
            field=models.ImageField(
                default="discountImage/сайт_морожка.jpg", upload_to="newsImage", verbose_name="Изображение для мобилки"
            ),
            preserve_default=False,
        ),
    ]
