# Generated by Django 4.2.5 on 2024-05-28 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0021_news_photo_medium_mobile_news_photo_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="photo_medium_mobile",
        ),
    ]
