# Generated by Django 4.2.5 on 2024-08-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_news_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploadFiles', verbose_name='Файл'),
        ),
    ]
