# Generated by Django 4.2.5 on 2024-08-12 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_news_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='endDateFile',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Файл Время окончания'),
        ),
        migrations.AddField(
            model_name='news',
            name='titleFile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название Файл'),
        ),
    ]
