# Generated by Django 4.2.5 on 2024-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_news_enddatefile_news_titlefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo_app',
            field=models.ImageField(blank=True, null=True, upload_to='newsImage', verbose_name='Изображение для приложения'),
        ),
    ]
