# Generated by Django 4.2.5 on 2024-09-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_news_photo_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть?'),
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для перехода'),
        ),
    ]
