# Generated by Django 4.2.5 on 2024-09-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_news_hide_news_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
    ]
