# Generated by Django 4.2.3 on 2023-09-08 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="productImage", verbose_name="Image of Product"
                    ),
                ),
                ("newPrice", models.FloatField(default=0)),
                ("oldPrice", models.FloatField(default=0)),
                ("percent", models.FloatField(default=0)),
                ("startDate", models.DateField(default=django.utils.timezone.now)),
                ("endDate", models.DateField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categoryProducts",
                        to="product.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
