# Generated by Django 4.2.5 on 2023-09-08 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="endDate",
            field=models.DateField(default=datetime.date(2023, 9, 8)),
        ),
        migrations.AlterField(
            model_name="product",
            name="startDate",
            field=models.DateField(default=datetime.date(2023, 9, 8)),
        ),
    ]
