# Generated by Django 4.2.3 on 2023-09-23 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_enddate_alter_product_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="endDate",
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
        migrations.AlterField(
            model_name="product",
            name="startDate",
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
    ]
