# Generated by Django 4.2.3 on 2023-09-24 09:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_category_options_alter_file_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("file", models.FileField(upload_to="uploadFiles", verbose_name="Файл")),
                ("endDate", models.DateField(default=django.utils.timezone.now, verbose_name="Время окончания")),
            ],
            options={
                "verbose_name": "Оферты",
                "verbose_name_plural": "Оферты",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="file",
            name="isCatalog",
            field=models.BooleanField(default=False, verbose_name="Оферты"),
        ),
    ]
