# Generated by Django 4.2.3 on 2023-09-24 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_catalogfile_file_iscatalog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="isCatalog",
        ),
    ]
