# Generated by Django 4.2.3 on 2023-09-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_remove_file_iscatalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="percent",
            field=models.IntegerField(default=0, verbose_name="Процент"),
        ),
    ]
