# Generated by Django 4.2.3 on 2023-10-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_product_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogfile",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="catalogfile",
            name="title_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="category",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="category",
            name="title_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="product",
            name="title_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
    ]
