# Generated by Django 4.2.5 on 2023-10-19 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_catalogfile_title_ru_catalogfile_title_uz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Высшая категория",
                "verbose_name_plural": "Высшая категория",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="top_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Top_categoryProducts",
                to="product.topcategory",
                verbose_name="Высшая категория",
            ),
        ),
    ]
