# Generated by Django 4.2.5 on 2023-10-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_topcategory_product_top_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="topcategory",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="topcategory",
            name="title_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
    ]
