# Generated by Django 4.2.5 on 2024-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_topcategory_title_ru_topcategory_title_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogfile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="topcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
