# Generated by Django 4.2.5 on 2024-01-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_catalogfile_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="images_file",
            field=models.FileField(
                default="img.png", upload_to="upload_image_files", verbose_name="Архив с изображениями"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="processed",
            field=models.IntegerField(default=0, verbose_name="Обработано"),
        ),
        migrations.AddField(
            model_name="file",
            name="total",
            field=models.IntegerField(default=0, verbose_name="Всего продуктов"),
        ),
    ]
