# Generated by Django 4.2.5 on 2024-01-18 13:58

import common.product.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_file_images_file_file_processed_file_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=common.product.models.upload_to, verbose_name="Image of Product"
            ),
        ),
    ]
