# Generated by Django 4.2.5 on 2024-05-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productregion_product_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='message',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
