# Generated by Django 4.2.5 on 2024-05-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_file_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
