# Generated by Django 4.2.5 on 2024-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть?'),
        ),
    ]
