# Generated by Django 4.2.5 on 2024-11-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_category_is_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isExclusive',
            field=models.BooleanField(default=False, verbose_name='Эксклюзивный?'),
        ),
    ]
