# Generated by Django 4.2.5 on 2024-12-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_isexclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isExclusive',
        ),
        migrations.AddField(
            model_name='product',
            name='promo_type',
            field=models.CharField(choices=[('exclusive', 'Эксклюзивно'), ('one2one', '1+1'), ('two2one', '2+1'), ('three2one', '3+1')], default=None, verbose_name='Тип акции'),
        ),
    ]
